/*-
 * Copyright © 2019 Diamond Light Source Ltd.
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

package org.eclipse.scanning.api.points.models;

import java.math.BigDecimal;

import org.eclipse.scanning.api.ModelValidationException;
import org.eclipse.scanning.api.annotation.ui.FieldDescriptor;

/**
 * Abstract superclass for models representing a raster scan within a rectangular box in two-dimensional space.
 */
public abstract class AbstractTwoAxisGridModel extends AbstractBoundingBoxModel {

	@FieldDescriptor(label="Orientation")
	private Orientation orientation = Orientation.HORIZONTAL;

	public enum Orientation {
		HORIZONTAL("Horizontal"), VERTICAL("Vertical");

		private final String orientationString;

		Orientation(String orientationString) {
	        this.orientationString = orientationString;
	    }

	    @Override
		public String toString() {
	        return this.orientationString;
	    }}

	/**
	 * By default the horizontal axis is the scanned first, i.e. is the fast axis. If this
	 * property is set the vertical axis is the scanned first.
	 *
	 * @return <code>true</code> if the vertical axis is scanned first, <code>false</code> if
	 * the horizontal axis is scanned first.
	 */

	public Orientation getOrientation() {
		return orientation;
	}

	public void setOrientation(Orientation orientation) {
		Orientation oldValue = this.orientation;
		this.orientation = orientation;
		this.pcs.firePropertyChange("orientation", oldValue, orientation);
	}

	public boolean isVerticalOrientation() {
		return orientation.equals(Orientation.VERTICAL);
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + (isVerticalOrientation() ? 1231 : 1237);
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (!super.equals(obj))
			return false;
		AbstractTwoAxisGridModel other = (AbstractTwoAxisGridModel) obj;
		return (orientation.equals(other.orientation));
	}

	@Override
	public String toString() {
		return "verticalOrientation=" + orientation
				+ ", " + super.toString();
	}

	/**
	 * Turns a StepModel into an equivalent PointsModel. Some scans (e.g XANES) perform similar scans but with small offsets,
	 * which can catch on floating point calculation errors, giving off-by-one in dataset shapes when reconstructing.
	 * This utility method prevents this situation by converting to a PointsModel, which will always have the same shape,
	 * and performing the division to find the number of points using BigDecimal.
	 * The BoundingBox of the returned model may differ from that of the input method, due to StepModels being
	 * able to leave a portion of a step towards their end too small for another step. PointsModel however use the entire region,
	 * so this partial box is equivalent in terms of point placement.
	 *
	 * @param model - a TwoAxisGridStepModel
	 * @return pointsModel - a TwoAxisGridPointsModel that will output IPositions that
	 * 						very closely match the IPositions generated by the input
	 */
	public static TwoAxisGridPointsModel enforceShape(TwoAxisGridStepModel model) {
		final TwoAxisGridPointsModel pointsModel = new TwoAxisGridPointsModel();
		if (!model.getName().equals("Raster")) {
			pointsModel.setName(model.getName());
		}
		pointsModel.setxAxisName(model.getxAxisName());
		pointsModel.setyAxisName(model.getyAxisName());
		pointsModel.setxAxisUnits(model.getxAxisUnits());
		pointsModel.setyAxisUnits(model.getyAxisUnits());
		pointsModel.setAlternating(model.isAlternating());
		pointsModel.setContinuous(model.isContinuous());
		pointsModel.setOrientation(model.getOrientation());

		final BoundingBox copy = new BoundingBox();
		final BoundingBox original = model.getBoundingBox();
		if (original != null) {
			copy.setxAxisName(original.getxAxisName());
			copy.setyAxisName(original.getyAxisName());
			copy.setxAxisStart(original.getxAxisStart());
			copy.setyAxisStart(original.getyAxisStart());
			copy.setxAxisLength(original.getxAxisLength());
			copy.setyAxisLength(original.getyAxisLength());
			copy.setRegionName(original.getRegionName());
		}
		final double xStep = model.getxAxisStep();
		final double yStep = model.getyAxisStep();

		final int xPoints = BigDecimal.valueOf(copy.getxAxisLength()).divideToIntegralValue(BigDecimal.valueOf(xStep)).intValue();
		final int yPoints = BigDecimal.valueOf(copy.getyAxisLength()).divideToIntegralValue(BigDecimal.valueOf(yStep)).intValue();

		if (xPoints < 0 || yPoints < 0) {
			throw new ModelValidationException("Steps must be in the same direction as the bounding box!", model, "xAxisStep", "yAxisStep");
		}

		/** If xStep > xAxisLength, the half step at the edges to allow for bounds will meet past the middle and would
		 * appear to run the scan backwards (and if the step was too long, exceed the boundingBox entirely). To ensure that
		 * behaviour is expected and consistent, we force any step that is longer than its bounding to lie in the middle of the
		 * axis.
		 */
		pointsModel.setxAxisPoints(Math.max(1, xPoints));
		pointsModel.setyAxisPoints(Math.max(1, yPoints));

		// Trim region that would not have been stepped in, unless 1 step in either direction which case retain
		// but place only a single point in the centre of the box, ignoring that the step was > half length

		if (xPoints > 1) {
			copy.setxAxisLength(xStep * xPoints);
		}
		if (yPoints > 1) {
			copy.setyAxisLength(yStep * yPoints);
		}
		pointsModel.setBoundingBox(copy);

		return pointsModel;
	}

}
