/*-
 * Copyright © 2020 Diamond Light Source Ltd.
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

package gda.device.detector.addetector.filewriter;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import gda.device.detector.nxdata.NXDetectorDataAppender;
import gda.device.detector.nxdata.NXDetectorDataHDF5FileLinkAppender;
import gda.device.detector.nxdata.NXDetectorSerialAppender;

/**
 * A File Writer class supports EPICS Area Detector producing multiple HDF5 files
 */
public class MultipleHDF5PluginsPerDetectorFileWriter extends MultipleImagesPerHDF5FileWriter {

	private static Logger logger = LoggerFactory.getLogger(MultipleHDF5PluginsPerDetectorFileWriter.class);

	@Override
	protected NXDetectorDataAppender createFileLinkAppender() {
		logger.trace("create file link appender to link to multiple HDF5 files generated by EPICS Area Detector plus additional PVs value collection if present");
		var nxDetectorDataHDF5FileLinkAppender = new NXDetectorDataHDF5FileLinkAppender(expectedFullFileName, getxPixelSize(), getyPixelSize(), getxPixelSizeUnit(), getyPixelSizeUnit(), getName(), dataRank);
		Optional<List<NXDetectorDataAppender>> optionalAppenders = getPvsToCollectMaps().map(this::createAppendersFromCollection);
		optionalAppenders.ifPresent(appenders -> appenders.add(nxDetectorDataHDF5FileLinkAppender));
		if (optionalAppenders.isPresent()) {
			return new NXDetectorSerialAppender(optionalAppenders.get());
		} else {
			return nxDetectorDataHDF5FileLinkAppender;
		}
	}
}
