/*-
 * Copyright © 2009 Diamond Light Source Ltd., Science and Technology
 * Facilities Council Daresbury Laboratory
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

package ide;

/**
 * This class is designed to test the appearance of an autogenerated class file. Following the genaration of a New Class
 * file - - tests.ide - NewClassTest - inherit from java.lang.object - tick all boxes except "final". compare with this
 * file. Then allow your file to autogenerate this top Javadoc comment by typing: "/**" and pressing return. *** An
 * empty comment block should be presented without any
 */
public abstract class NewClassTest {

	/**
	 * 
	 */
	public NewClassTest() {
		super();
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		// TODO Auto-generated method stub

	}

}
