/*-
 * Copyright © 2013 Diamond Light Source Ltd.
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

package uk.ac.gda.exafs.ui;

import gda.configuration.properties.LocalProperties;
import gda.exafs.scan.ExafsScanPointCreator;
import gda.exafs.scan.ExafsScanPointCreatorException;
import gda.exafs.scan.ExafsTimeEstimator;
import gda.exafs.scan.XanesScanPointCreator;
import gda.jython.JythonServerFacade;
import gda.util.exafs.Element;

import java.lang.reflect.Method;
import java.net.URL;
import java.text.DateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.TimeZone;

import org.dawb.common.ui.widgets.ActionBarWrapper;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.Status;
import org.eclipse.core.runtime.jobs.Job;
import org.eclipse.dawnsci.analysis.dataset.impl.Dataset;
import org.eclipse.dawnsci.analysis.dataset.impl.DoubleDataset;
import org.eclipse.dawnsci.analysis.dataset.impl.IntegerDataset;
import org.eclipse.dawnsci.plotting.api.IPlottingSystem;
import org.eclipse.dawnsci.plotting.api.PlotType;
import org.eclipse.dawnsci.plotting.api.PlottingFactory;
import org.eclipse.dawnsci.plotting.api.trace.ILineTrace;
import org.eclipse.dawnsci.plotting.api.trace.ITrace;
import org.eclipse.jface.preference.PreferenceDialog;
import org.eclipse.richbeans.api.event.ValueAdapter;
import org.eclipse.richbeans.api.event.ValueEvent;
import org.eclipse.richbeans.reflection.RichBeanUtils;
import org.eclipse.richbeans.widgets.FieldComposite.NOTIFY_TYPE;
import org.eclipse.richbeans.widgets.scalebox.ScaleBox;
import org.eclipse.richbeans.widgets.wrappers.ComboWrapper;
import org.eclipse.richbeans.widgets.wrappers.LabelWrapper;
import org.eclipse.swt.SWT;
import org.eclipse.swt.custom.ScrolledComposite;
import org.eclipse.swt.graphics.Color;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Group;
import org.eclipse.swt.widgets.Label;
import org.eclipse.ui.IEditorInput;
import org.eclipse.ui.IEditorSite;
import org.eclipse.ui.PartInitException;
import org.eclipse.ui.dialogs.PreferencesUtil;
import org.eclipse.ui.forms.events.ExpansionAdapter;
import org.eclipse.ui.forms.events.ExpansionEvent;
import org.eclipse.ui.forms.widgets.ExpandableComposite;
import org.python.core.PyObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import uk.ac.diamond.scisoft.analysis.axis.AxisValues;
import uk.ac.gda.beans.exafs.XanesScanParameters;
import uk.ac.gda.beans.exafs.XasScanParameters;
import uk.ac.gda.exafs.ui.preferences.ExafsEditorPreferencePage;
import uk.ac.gda.richbeans.editors.DirtyContainer;
import uk.ac.gda.richbeans.editors.RichBeanEditorPart;
import uk.ac.gda.util.beans.BeansFactory;
import uk.ac.gda.util.schema.SchemaReader;

/**
 * Class does not need to be public but is made so here so that tests can access it.
 */
public abstract class ElementEdgeEditor extends RichBeanEditorPart {

	protected enum ELEMENT_EVENT_TYPE {INIT, ELEMENT_CHANGE, EDGE_CHANGE, ENERGY_CHANGE}

	private static Logger logger = LoggerFactory.getLogger(ElementEdgeEditor.class);

	protected ComboWrapper edge;
	protected ComboWrapper element;
	protected ScrolledComposite scrolledComposite;
	protected Composite container;
	protected Label estimatePointsLabel;
	protected Label estimateTimeLabel;
	protected Composite expandContainer;
	protected IPlottingSystem<Composite> plottingsystem;
	protected ActionBarWrapper plottingsystemActionBarWrapper;
	protected AxisValues xAxisValues;
	protected volatile boolean suspendGraphUpdate = false;
	protected Object lastPlottedBean;
	// Two two fields are currently not automatically used in the Xas editor as scientists have requested that they not
	// be there as they are autogenerated.
	private LabelWrapper coreHoleValueLabel;
	private ScaleBox edgeEnergyLabel;
	protected boolean updateValueAllowed = true;
	private Color red, black;
	protected PlotUpdateJob plotUpdateJob;

	public ElementEdgeEditor(String path, URL mappingURL, DirtyContainer dirtyContainer, Object editingBean) {
		super(path, mappingURL, dirtyContainer, editingBean);
		plotUpdateJob = new PlotUpdateJob("Calculating energy profile");
	}

	@Override
	public void init(IEditorSite site, IEditorInput input) throws PartInitException {
		try {
			plottingsystem = PlottingFactory.createPlottingSystem();
		} catch (Exception e) {
			throw new PartInitException("Exception creating PlottingSystem in ElementEdgeEditor");
		}
		super.init(site, input);
	}

	/**
	 * You can override this method and call it at the start of your implementation.
	 */
	protected void createEstimationComposite(final Composite right) {
		Composite topRight = new Composite(right, SWT.NONE);
		topRight.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false));
		topRight.setLayout(new GridLayout(2, false));

		Label estimatedNumberOfLabel = new Label(topRight, SWT.NONE);
		estimatedNumberOfLabel.setLayoutData(new GridData(SWT.LEFT, SWT.CENTER, false, false));
		estimatedNumberOfLabel.setText("Number of scan points     ");
		estimatePointsLabel = new Label(topRight, SWT.NONE);
		estimatePointsLabel.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false));

		Label estimatedTimeLabel = new Label(topRight, SWT.NONE);
		estimatedTimeLabel.setLayoutData(new GridData(SWT.LEFT, SWT.CENTER, false, false));
		estimatedTimeLabel.setText("Estimated time     ");
		estimatedTimeLabel.setToolTipText("The sum of all data points, does not include the overhead for moving the mono etc.");
		estimateTimeLabel = new Label(topRight, SWT.NONE);
		estimateTimeLabel.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, true, false));

		ExpandableComposite xasScanExpandableComposite = new ExpandableComposite(right, ExpandableComposite.COMPACT | ExpandableComposite.TWISTIE);
		xasScanExpandableComposite.marginWidth = 5;
		xasScanExpandableComposite.marginHeight = 5;
		xasScanExpandableComposite.setText("EXAFS Graph");
		xasScanExpandableComposite.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));

		Composite plotArea = new Composite(xasScanExpandableComposite, SWT.NONE);
		GridLayout grid = new GridLayout(1, false);
		grid.marginBottom = 0;
		grid.marginTop = 0;
		grid.horizontalSpacing = 0;
		grid.marginWidth = 0;
		grid.verticalSpacing = 0;
		grid.marginHeight = 0;
		plotArea.setLayout(grid);

		plottingsystemActionBarWrapper = ActionBarWrapper.createActionBars(plotArea, null);
		plottingsystem.createPlotPart(plotArea, getTitle(), null, PlotType.XY, this);
		plottingsystem.getPlotActionSystem().fillZoomActions(plottingsystemActionBarWrapper.getToolBarManager());
		plottingsystem.getPlotComposite().setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));
		plottingsystemActionBarWrapper.update(true);

		plotUpdateJob.createTrace();

		xasScanExpandableComposite.setClient(plotArea);

		xAxisValues = new AxisValues();

		xasScanExpandableComposite.addExpansionListener(new ExpansionAdapter() {
			@Override
			public void expansionStateChanged(ExpansionEvent e) {
				updateLayout();
			}
		});

	}

	@Override
	public void linkUI(final boolean isPageChange) {
		super.linkUI(isPageChange);
		try {
			controller.addValueListener(new ValueAdapter("Element Edge Bean Listener") {
				@Override
				public void valueChangePerformed(ValueEvent e) {
					getSite().getShell().getDisplay().asyncExec(new Runnable() {
						@Override
						public void run() {
							try {
								if (!suspendGraphUpdate && updateValueAllowed){
									updatePlottedPoints();
									updatePointsLabels();
								}
							} catch (Exception e1) {
								logger.error("Cannot update plot of points.", e1);
							}
						}
					});
				}
			});
		} catch (Exception e1) {
			logger.error("Cannot add listener to ui " + editingBean.getClass().getName(), e1);
		}
	}

	@Override
	protected List<String> getExpressionFields() throws Exception {
		if (expressionFields == null) {
			expressionFields = controller.getEditingFields();
			expressionFields.add("edge");
		}
		return expressionFields;
	}

	@Override
	public Object getFieldValue(final String fieldName) throws Exception {
		if ("edge".equals(fieldName))
			return edgeEnergyLabel.getNumericValue();
		return getField(fieldName).getValue();
	}

	public void updatePlottedPoints() {
		try {
			updateFromUIAndReturnEditingBean();
		} catch (Exception e) {
			logger.error("Exception updating from UI. This may cause instabilities in the editor.", e);
		}
		plotUpdateJob.plot();
	}

	/** Override to provide additional lines to the edge value. */
	protected String[] getLineLabels() {
		return new String[] { "Edge" };
	}

	/** Override to provide additional lines to the edge value. */
	protected double[] getLineValues() {
		return new double[] { getEdgeValue() };
	}

	/** Override to provide additional lines to the edge value. */
	protected java.awt.Color[] getLineColours() {
		return new java.awt.Color[] { java.awt.Color.RED };
	}

	protected void updateLayout() {
		container.layout();
		expandContainer.layout();
		scrolledComposite.setMinSize(container.computeSize(SWT.DEFAULT, SWT.DEFAULT));
	}

	protected void createElementEdgeArea(Group main) {
		Composite left = new Composite(main, SWT.NONE);
		left.setLayoutData(new GridData(SWT.LEFT, SWT.TOP, false, false));
		GridLayout gridLayout_2 = new GridLayout();
		gridLayout_2.numColumns = 2;
		left.setLayout(gridLayout_2);

		Label elementLabel = new Label(left, SWT.NONE);
		elementLabel.setText("Element");

		element = new ComboWrapper(left, SWT.DROP_DOWN);
		element.setTextLimit(2);
		GridData gd_element = new GridData(SWT.FILL, SWT.CENTER, true, false);
		gd_element.minimumWidth = 100;
		gd_element.widthHint = 100;
		element.setLayoutData(gd_element);

		Label edgeLabel = new Label(left, SWT.NONE);
		edgeLabel.setText("Edge");

		edge = new ComboWrapper(left, SWT.READ_ONLY);

		Label e2Label = new Label(left, SWT.NONE);
		e2Label.setText("Edge Energy");

		edgeEnergyLabel = new ScaleBox(left, SWT.NONE);
		edgeEnergyLabel.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, false, false));
		edgeEnergyLabel.setUnit("eV");
		edgeEnergyLabel.setNotifyType(NOTIFY_TYPE.VALUE_CHANGED);
		edgeEnergyLabel.on();

		if (LocalProperties.get("gda.beamline.name").equals("b18")) {
			String dcmCrystal = JythonServerFacade.getInstance().evaluateCommand("dcm_crystal()");
			if (dcmCrystal.equals("Si(111)")) {
				edgeEnergyLabel.setMaximum(26000.0);
				edgeEnergyLabel.setMinimum(2050.0);
			}
			else if (dcmCrystal.equals("Si(311)")) {
				edgeEnergyLabel.setMaximum(40000.0);
				edgeEnergyLabel.setMinimum(4000.0);
			}
		}
		else
			edgeEnergyLabel.setMaximum(40000.0);
		controller.addBeanField("EdgeEnergy", edgeEnergyLabel);
		Label coreHoleLabel = new Label(left, SWT.NONE);
		coreHoleLabel.setText("Core Hole");
		coreHoleValueLabel = new LabelWrapper(left, SWT.NONE);
		coreHoleValueLabel.setLayoutData(new GridData(SWT.FILL, SWT.CENTER, false, false));
		coreHoleValueLabel.setUnit("eV");
		coreHoleValueLabel.setActive(false);
		GridData gd_edge = new GridData(SWT.FILL, SWT.CENTER, true, false);
		edge.setLayoutData(gd_edge);
	}

	/**
	 * @param objectName
	 * @return SchemaReader
	 * @throws Exception
	 */
	protected SchemaReader setupElementAndEdge(final String objectName) throws Exception {
		element.setItems(Element.getSortedEdgeSymbols("P", "Np"));

		SchemaReader reader = new SchemaReader(XasScanParameters.schemaUrl);
		List<String> choices = reader.getAllowedChoices(objectName, "edge");
		edge.setItems(choices.toArray(new String[choices.size()]));

		element.addValueListener(new ValueAdapter("elementListener") {
			@Override
			public void valueChangePerformed(ValueEvent e) {
				try {
					setPointsUpdate(false);
					updateElement(ELEMENT_EVENT_TYPE.ELEMENT_CHANGE);
				} catch (Exception e1) {
					logger.error("Cannot update element.", e1);
				} finally {
					setPointsUpdate(true);
				}
			}
		});
		edge.addValueListener(new ValueAdapter("edgeListener") {
			@Override
			public void valueChangePerformed(ValueEvent e) {
				try {
					setPointsUpdate(false);
					updateElement(ELEMENT_EVENT_TYPE.EDGE_CHANGE);
				} catch (Exception e1) {
					logger.error("Cannot update element.", e1);
				} finally {
					setPointsUpdate(true);
				}
			}
		});
		edgeEnergyLabel.addValueListener(new ValueAdapter("energyListener") {
			@Override
			public void valueChangePerformed(ValueEvent e) {
				try {
					setPointsUpdate(false);
					updateElement(ELEMENT_EVENT_TYPE.ENERGY_CHANGE);
				} catch (Exception e1) {
					logger.error("Cannot update element.", e1);
				} finally {
					setPointsUpdate(true);
				}
			}
		});

		return reader;
	}

	protected void setPointsUpdate(boolean isUpdate) {
		updateValueAllowed = isUpdate;
		if (isUpdate) {
			updatePointsLabels();
			edge.on();
			element.on();
		}
		else{
			edge.off();
			element.off();
		}
	}

	/*
	 * Can override to provide a different points list.
	 *
	 * @return points
	 * @throws Exception
	 */
	@SuppressWarnings("unchecked")
	protected List<PyObject[]> getScanPoints(final Object currentBean) throws Exception {
		List<PyObject[]> points = null;
		if (editingBean instanceof XanesScanParameters)
			points = XanesScanPointCreator.calculateEnergies((XanesScanParameters) currentBean);
		else if (editingBean instanceof XasScanParameters)
			points = ExafsScanPointCreator.calculateEnergies((XasScanParameters) currentBean);
		return points;
	}

	protected void updatePointsLabels() {
		try {
			List<PyObject[]> points = getScanPoints(updateFromUIAndReturnEditingBean());
			if (points == null || points.isEmpty())
				throw new Exception("Cannot esitmate points!");
			if(estimatePointsLabel!=null){
				estimatePointsLabel.setText(points.size() + " points");
				estimatePointsLabel.setForeground(Display.getCurrent().getSystemColor(SWT.COLOR_BLACK));
			}
			long time = ExafsTimeEstimator.getTime(points);
			Date date = new Date(time);
			DateFormat format = DateFormat.getTimeInstance(DateFormat.MEDIUM, Locale.UK);
			format.setCalendar(Calendar.getInstance(TimeZone.getTimeZone("GMT")));
			if(estimateTimeLabel!=null){
				estimateTimeLabel.setText(format.format(date));
				estimateTimeLabel.setForeground(Display.getCurrent().getSystemColor(SWT.COLOR_BLACK));
			}
		} catch(ExafsScanPointCreatorException e){
			if(estimatePointsLabel!=null){
				estimatePointsLabel.setText(e.getMessage());
				estimatePointsLabel.setForeground(Display.getCurrent().getSystemColor(SWT.COLOR_RED));
			}
			if(estimateTimeLabel!=null){
				estimateTimeLabel.setText(e.getMessage());
				estimateTimeLabel.setForeground(Display.getCurrent().getSystemColor(SWT.COLOR_RED));
			}
		}catch (Exception ne) {
			if(estimatePointsLabel!=null)
				estimatePointsLabel.setText("-");
			if(estimateTimeLabel!=null)
				estimateTimeLabel.setText("-");
		}
		if(expandContainer!=null)
			expandContainer.layout();
	}

	protected Object fetchEditingBean() {
		return editingBean;
	}

	protected void updateElement(ELEMENT_EVENT_TYPE type) throws Exception {
		try {
			Element element = getSelectedElement(type);
			if (element == null)
				return;
			String edgeValue = getEdgeUseBean();
			if (type == ELEMENT_EVENT_TYPE.INIT || type == ELEMENT_EVENT_TYPE.ELEMENT_CHANGE) {
				List<String> edges = element.getAllowedEdges();
				edge.setItems(edges.toArray(new String[edges.size()]));
				if (edgeValue != null && !edge.isDisposed()) {
					if (edges.contains(edgeValue))
						edge.setValue(edgeValue);
					else
						edge.setValue(edges.get(0));
				}
				else {
					try {
						Method method = editingBean.getClass().getMethod("getEdge");
						if (!edge.isDisposed())
							edge.setValue(method.invoke(editingBean));
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
				if (edge.getSelectionIndex() < 0)
					edge.select(0);
			}
			if (type == ELEMENT_EVENT_TYPE.ENERGY_CHANGE)
				return;
			if (edgeValue == null)
				return;
			double coreHole = element.getCoreHole(edgeValue);
			getCoreHole().setValue(coreHole);
			double edgeEn = element.getEdgeEnergy(edgeValue);
			getEdgeEnergy().setValue(edgeEn); // Its in eV in Element.
		} finally {
		}
	}

	protected Element getSelectedElement(ELEMENT_EVENT_TYPE type) throws Exception {
		Element ele = getElementUseBean();
		if (ele == null && type != ELEMENT_EVENT_TYPE.INIT) {
			if (red == null || red.isDisposed())
				red = getSite().getShell().getDisplay().getSystemColor(SWT.COLOR_RED);
			element.setForeground(red);
			return null;
		}
		if (black == null || black.isDisposed())
			black = getSite().getShell().getDisplay().getSystemColor(SWT.COLOR_BLACK);
		element.setForeground(black);
		return ele;
	}

	@Override
	public void dispose() {
		if (plottingsystem != null) {
			plottingsystem.dispose();
			plottingsystem = null;
		}
		super.dispose();
	}

	protected Element getElementUseBean() throws Exception {
		String symbol = (String) element.getValue();
		if (symbol == null || "".equals(symbol))
			symbol = (String) RichBeanUtils.getBeanValue(editingBean, "element");
		return Element.getElement(symbol);
	}

	protected String getEdgeUseBean() throws Exception {
		String edgeName = (String) edge.getValue();
		if (edgeName == null || "".equals(edgeName))
			edgeName = (String) RichBeanUtils.getBeanValue(editingBean, "edge");
		return edgeName;
	}

	/**
	 * Returns the edge value in eV. Uses the bean if value is not in the ui.
	 *
	 * @return edge
	 */
	protected double getEdgeValue() {
		try {
			double edgeVal = edgeEnergyLabel.getNumericValue();
			if (edgeVal > 0 && !Double.isNaN(edgeVal) && !Double.isInfinite(edgeVal))
				return edgeVal;
			Element ele = getElementUseBean();
			String edge = getEdgeUseBean();
			return ele.getEdgeEnergy(edge);
		} catch (Exception e) {
			logger.error("Cannot parse: " + edgeEnergyLabel.getValue(), e);
			return 0d;
		}
	}

	protected LabelWrapper getCoreHole() {
		return coreHoleValueLabel;
	}

	public ScaleBox getEdgeEnergy() {
		return edgeEnergyLabel;
	}

	@Override
	public void setFocus() {
		if (container != null)
			container.setFocus();
	}

	protected void openPreferences() {
		PreferenceDialog pref = PreferencesUtil.createPreferenceDialogOn(getSite().getShell(), ExafsEditorPreferencePage.ID, null, null);
		if (pref != null)
			pref.open();
	}

	final class PlotUpdateJob extends Job {
		protected ILineTrace exafsProfile;
		private boolean first = true;

		public PlotUpdateJob(String name) {
			super(name);
			setPriority(Job.INTERACTIVE);
			setUser(true);
			setSystem(true);
		}

		public void createTrace() {
			IntegerDataset x = IntegerDataset.createRange(5);
			IntegerDataset y = IntegerDataset.createRange(5);
			x.setName("Energy (eV)");
			y.setName("\u0394E (eV)");
			List<ITrace> traces = plottingsystem.createPlot1D(x, Arrays.asList(new Dataset[] { y }), null);
			exafsProfile = (ILineTrace) traces.get(0);
			exafsProfile.setTraceColor(Display.getDefault().getSystemColor(SWT.COLOR_BLACK));
		}

		public void plot() {
			cancel();
			schedule();
		}

		@Override
		protected IStatus run(final IProgressMonitor monitor) {
			try {
				Object scanBean = editingBean;
				if (monitor.isCanceled())
					return Status.CANCEL_STATUS;
				if (lastPlottedBean != null && lastPlottedBean.equals(scanBean))
					return Status.CANCEL_STATUS;
				if (monitor.isCanceled())
					return Status.CANCEL_STATUS;
				List<PyObject[]> points = getScanPoints(editingBean);
				double[] y = new double[points.size()];
				double[] x = new double[points.size()];
				double previousEnergy = -1;
				for (int i = 0; i < points.size(); i++) {
					double energy = points.get(i)[0].asDouble();
					x[i] = energy;
					Double delta = 0d;
					if (previousEnergy > -1)
						delta = energy - previousEnergy;
					y[i] = delta;
					previousEnergy = energy;
				}
				y[0] = y[1];
				final DoubleDataset xDataSet = new DoubleDataset(x, x.length);
				final DoubleDataset yDataSet = new DoubleDataset(y, y.length);
				xDataSet.setName("Energy (eV)");
				yDataSet.setName("\u0394E (eV)");
				Display.getDefault().syncExec(new Runnable() {
					@Override
					public void run() {
						// We just replot it.
						exafsProfile.setTraceColor(Display.getDefault().getSystemColor(SWT.COLOR_BLACK));
						exafsProfile.setData(xDataSet, yDataSet);
						if (first) {
							plottingsystem.repaint();
							first = false;
						}
						plottingsystem.autoscaleAxes();
					}
				});
				lastPlottedBean = BeansFactory.deepClone(scanBean);
				return Status.OK_STATUS;
			} catch (Throwable no) {
				lastPlottedBean = null;
				Display.getDefault().syncExec(new Runnable() {
					@Override
					public void run() {
						// We just replot it.
						exafsProfile.setTraceColor(Display.getDefault().getSystemColor(SWT.COLOR_RED));
					}
				});
				return Status.CANCEL_STATUS;
			}
		}

	}
	public ComboWrapper getEdge() {
		return edge;
	}

	public ComboWrapper getElement() {
		return element;
	}
}
