/*-
 * Copyright © 2009 Diamond Light Source Ltd.
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _BEAM_IDL_
#define _BEAM_IDL_

#include <device.idl>

module gda {
module beamline {
module beam {
module corba {

/**
 *  An interface for a distributed object holding important values which
 *  client and server-side objects need to share.
 */
interface CorbaBeamInfo : _factory::corba::CorbaFindable
{
    void setWavelength(in double value);
    double getWavelength();
    void setEnergy(in double value);
    double getEnergy();
    void setEnergyFromDCM()
      raises (device::corba::CorbaDeviceException);
    boolean isCalibrated();

};

};};};};

#endif
