/*-
 * Copyright © 2009 Diamond Light Source Ltd., Science and Technology
 * Facilities Council Daresbury Laboratory
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

#include <device.idl>

module gda {
module util {
module lookupFileWriter {
module corba {

	typedef sequence<string> stringarray;
/**
 * An Interface for Distributed Header File Writer class
 */

interface CorbaLookupFileWriter : gda::_factory::corba::CorbaFindable
{
   void  setFileName(in string fileName)
      raises (device::corba::CorbaDeviceException);

   void setFileHeader(in stringarray headers)
      raises (device::corba::CorbaDeviceException);

   void write(in stringarray values)
      raises (device::corba::CorbaDeviceException);

   void addToFile(in stringarray values)
      raises (device::corba::CorbaDeviceException);
};

};};};};
