/*-
 * Copyright © 2009 Diamond Light Source Ltd., Science and Technology
 * Facilities Council Daresbury Laboratory
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _PHANTOM_IDL_
#define _PHANTOM_IDL_

#include <detector.idl>

module gda {
module device {
module detector {
module phantom {
module corba {

/**
 * An interface for a distributed motor class
 */ 
 
interface CorbaPhantom : device::detector::corba::CorbaDetector
{
	void setUpForCollection(in long numberOfFrames, in long framesPerSecond, in long width, in long height)
			raises (device::corba::CorbaDeviceException);

	any retrieveData(in long cineNumber, in long start, in long count) raises (device::corba::CorbaDeviceException);

	string command(in string commandString) raises (device::corba::CorbaDeviceException);

}; 


};};};};};

#endif
