/*-
 * Copyright © 2009 Diamond Light Source Ltd., Science and Technology
 * Facilities Council Daresbury Laboratory
 *
 * This file is part of GDA.
 *
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _SCANNABLEMOTION_IDL_
#define _SCANNABLEMOTION_IDL_

#include <scannable.idl>

module gda {
module device {
module scannable {
module corba {

/**
 *  An interface for distributed Scannable classes which represent a number
 *  or an array of numbers which they can alter via the getPosition method
 */
interface CorbaScannableMotion : device::scannable::corba::CorbaScannable
{
	
};

};};};};

#endif

