/**
 *
 * $Id$
 */
package org.opengda.detector.electronanalyser.model.regiondefinition.api.validation;

import org.opengda.detector.electronanalyser.model.regiondefinition.api.Sequence;

/**
 * A sample validator interface for {@link org.opengda.detector.electronanalyser.model.regiondefinition.api.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
	boolean validate();

	boolean validateSequence(Sequence value);
}
