/**
 *
 * $Id$
 */
package org.opengda.detector.electronanalyser.model.regiondefinition.api.validation;

import org.eclipse.emf.common.util.EList;

import org.opengda.detector.electronanalyser.model.regiondefinition.api.RUN_MODES;
import org.opengda.detector.electronanalyser.model.regiondefinition.api.Region;
import org.opengda.detector.electronanalyser.model.regiondefinition.api.Spectrum;

/**
 * A sample validator interface for {@link org.opengda.detector.electronanalyser.model.regiondefinition.api.Sequence}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SequenceValidator {
	boolean validate();

	boolean validateFilename(String value);
	boolean validateRegion(EList<Region> value);
	boolean validateRunMode(RUN_MODES value);
	boolean validateRunModeIndex(int value);
	boolean validateNumIterations(int value);
	boolean validateNumInterationOption(boolean value);
	boolean validateRepeatUntilStopped(boolean value);
	boolean validateConfirmAfterEachIteration(boolean value);
	boolean validateSpectrum(Spectrum value);
	boolean validateElementSet(String value);
}
