/**
 *
 * $Id$
 */
package org.opengda.detector.electronanalyser.model.regiondefinition.api.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.opengda.detector.electronanalyser.model.regiondefinition.api.Spectrum}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SpectrumValidator {
	boolean validate();

	boolean validateLocation(String value);
	boolean validateUser(String value);
	boolean validateSampleName(String value);
	boolean validateFilenamePrefix(String value);
	boolean validateBaseDirectory(String value);
	boolean validateFilenameFormat(String value);
	boolean validateFileExtension(String value);
	boolean validateNumberOfComments(int value);
	boolean validateComments(EList<String> value);
}
