/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gda_analysis_numerical_fourier_FFTWComplex */

#ifndef _Included_gda_analysis_numerical_fourier_FFTWComplex
#define _Included_gda_analysis_numerical_fourier_FFTWComplex
#ifdef __cplusplus
extern "C" {
#endif
#undef gda_analysis_numerical_fourier_FFTWComplex_FORWARD
#define gda_analysis_numerical_fourier_FFTWComplex_FORWARD 1L
#undef gda_analysis_numerical_fourier_FFTWComplex_BACKWARD
#define gda_analysis_numerical_fourier_FFTWComplex_BACKWARD -1L
#undef gda_analysis_numerical_fourier_FFTWComplex_EXHAUSTIVE
#define gda_analysis_numerical_fourier_FFTWComplex_EXHAUSTIVE 8L
#undef gda_analysis_numerical_fourier_FFTWComplex_PATIENT
#define gda_analysis_numerical_fourier_FFTWComplex_PATIENT 32L
#undef gda_analysis_numerical_fourier_FFTWComplex_ESTIMATE
#define gda_analysis_numerical_fourier_FFTWComplex_ESTIMATE 64L
/*
 * Class:     gda_analysis_numerical_fourier_FFTWComplex
 * Method:    nativeOneDimensional
 * Signature: ([D[DII)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWComplex_nativeOneDimensional
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     gda_analysis_numerical_fourier_FFTWComplex
 * Method:    nativeTwoDimensional
 * Signature: (II[D[DII)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWComplex_nativeTwoDimensional
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jint, jint);

/*
 * Class:     gda_analysis_numerical_fourier_FFTWComplex
 * Method:    nativeThreeDimensional
 * Signature: (III[D[DII)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWComplex_nativeThreeDimensional
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jdoubleArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
