/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gda_analysis_numerical_fourier_FFTWReal */

#ifndef _Included_gda_analysis_numerical_fourier_FFTWReal
#define _Included_gda_analysis_numerical_fourier_FFTWReal
#ifdef __cplusplus
extern "C" {
#endif
#undef gda_analysis_numerical_fourier_FFTWReal_FORWARD
#define gda_analysis_numerical_fourier_FFTWReal_FORWARD 1L
#undef gda_analysis_numerical_fourier_FFTWReal_BACKWARD
#define gda_analysis_numerical_fourier_FFTWReal_BACKWARD -1L
#undef gda_analysis_numerical_fourier_FFTWReal_EXHAUSTIVE
#define gda_analysis_numerical_fourier_FFTWReal_EXHAUSTIVE 8L
#undef gda_analysis_numerical_fourier_FFTWReal_PATIENT
#define gda_analysis_numerical_fourier_FFTWReal_PATIENT 32L
#undef gda_analysis_numerical_fourier_FFTWReal_ESTIMATE
#define gda_analysis_numerical_fourier_FFTWReal_ESTIMATE 64L
/*
 * Class:     gda_analysis_numerical_fourier_FFTWReal
 * Method:    nativeOneDimensionalForward
 * Signature: ([D[DI)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWReal_nativeOneDimensionalForward
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     gda_analysis_numerical_fourier_FFTWReal
 * Method:    nativeOneDimensionalBackward
 * Signature: ([D[DI)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWReal_nativeOneDimensionalBackward
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     gda_analysis_numerical_fourier_FFTWReal
 * Method:    nativeTwoDimensionalForward
 * Signature: (II[D[DI)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWReal_nativeTwoDimensionalForward
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     gda_analysis_numerical_fourier_FFTWReal
 * Method:    nativeTwoDimensionalBackward
 * Signature: (II[D[DI)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWReal_nativeTwoDimensionalBackward
  (JNIEnv *, jobject, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     gda_analysis_numerical_fourier_FFTWReal
 * Method:    nativeThreeDimensionalForward
 * Signature: (III[D[DI)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWReal_nativeThreeDimensionalForward
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     gda_analysis_numerical_fourier_FFTWReal
 * Method:    nativeThreeDimensionalBackward
 * Signature: (III[D[DI)V
 */
JNIEXPORT void JNICALL Java_gda_analysis_numerical_fourier_FFTWReal_nativeThreeDimensionalBackward
  (JNIEnv *, jobject, jint, jint, jint, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
