/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gda_util_LibGdaCommon */

#ifndef _Included_gda_util_LibGdaCommon
#define _Included_gda_util_LibGdaCommon
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gda_util_LibGdaCommon
 * Method:    _getFullNameOfUser
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_gda_util_LibGdaCommon__1getFullNameOfUser
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
