/**
 *
 * $Id$
 */
package org.opengda.lde.model.ldeexperiment.validation;

import org.eclipse.emf.common.util.EList;

import org.opengda.lde.model.ldeexperiment.Sample;

/**
 * A sample validator interface for {@link org.opengda.lde.model.ldeexperiment.SampleList}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SampleListValidator {
	boolean validate();

	boolean validateFilename(String value);
	boolean validateSample(EList<Sample> value);
}
