/**
 *
 * $Id$
 */
package org.opengda.lde.model.ldeexperiment.validation;

import java.util.Date;
import org.opengda.lde.model.ldeexperiment.STATUS;

/**
 * A sample validator interface for {@link org.opengda.lde.model.ldeexperiment.Sample}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SampleValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateSampleID(String value);
	boolean validateStatus(STATUS value);
	boolean validateActive(boolean value);

	boolean validateEnabled(boolean value);
	boolean validateCellID(String value);
	boolean validateVisitID(String value);
	boolean validateEmail(String value);
	boolean validateCommand(String value);
	boolean validateComment(String value);

	boolean validateStartDate(Date value);

	boolean validateEndDate(Date value);

	boolean validateMailCount(int value);

	boolean validateDataFileCount(int value);

	boolean validateDataFilePath(String value);

	boolean validateCalibrant(String value);
}
