/*******************************************************************************
 * Copyright © 2009, 2014 Diamond Light Source Ltd
 *
 * This file is part of GDA.
 *  
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 *
 * Contributors:
 * 	Diamond Light Source Ltd
 *******************************************************************************/
/**
 *
 * $Id$
 */
package org.opengda.lde.model.ldeexperiment.validation;

import java.util.Date;

import org.opengda.lde.model.ldeexperiment.Cell;
import org.opengda.lde.model.ldeexperiment.STATUS;

/**
 * A sample validator interface for {@link org.opengda.lde.model.ldeexperiment.Sample}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SampleValidator {
	boolean validate();

	boolean validateCell(Cell value);

	boolean validateSampleID(String value);
	boolean validateStatus(STATUS value);
	boolean validateActive(boolean value);
	boolean validateName(String value);
	boolean validateCellID(String value);
	boolean validateVisitID(String value);
	boolean validateCalibrant(String value);
	boolean validateCalibrant_x(double value);
	boolean validateCalibrant_y(double value);
	boolean validateCalibrant_exposure(double value);
	boolean validateSample_x_start(Double value);
	boolean validateSample_x_stop(Double value);
	boolean validateSample_x_step(Double value);
	boolean validateSample_y_start(Double value);
	boolean validateSample_y_stop(Double value);
	boolean validateSample_y_step(Double value);
	boolean validateSample_exposure(double value);
	boolean validateDetector_x(double value);
	boolean validateDetector_y(double value);
	boolean validateDetector_z(double value);
	boolean validateEmail(String value);
	boolean validateStartDate(Date value);
	boolean validateEndDate(Date value);
	boolean validateCommand(String value);
	boolean validateDriveID(String value);
	boolean validateMailCount(int value);
	boolean validateDataFileCount(int value);
	boolean validateComment(String value);
	boolean validateCalibrationFilePath(String value);

	boolean validateDataFilePath(String value);
}
