/*******************************************************************************
 * Copyright © 2009, 2015 Diamond Light Source Ltd
 *
 * This file is part of GDA.
 *  
 * GDA is free software: you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 3 as published by the Free
 * Software Foundation.
 *
 * GDA is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along
 * with GDA. If not, see <http://www.gnu.org/licenses/>.
 *
 * Contributors:
 * 	Diamond Light Source Ltd
 *******************************************************************************/
/**
 *
 * $Id$
 */
package org.opengda.lde.model.ldeexperiment.validation;

import org.eclipse.emf.common.util.EList;

import org.opengda.lde.model.ldeexperiment.Cell;
import org.opengda.lde.model.ldeexperiment.Experiment;

/**
 * A sample validator interface for {@link org.opengda.lde.model.ldeexperiment.Stage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StageValidator {
	boolean validate();

	boolean validateStageID(String value);
	boolean validateCells(EList<Cell> value);
	boolean validateDetector_x(double value);
	boolean validateDetector_y(double value);
	boolean validateDetector_z(double value);
	boolean validateCamera_x(double value);
	boolean validateCamera_y(double value);
	boolean validateCamera_z(double value);

	boolean validateNumberOfCells(int value);

	boolean validateExperiment(Experiment value);
}
